### ISSUE TITLE
hello!it's me again, thanks for the guide u gave me before and I fixed that bug,but I met another problem!

### ISSUE THREAD

**Issue by ANYMS-A** [hollance/TensorFlow-iOS-Example#2]
crissallandeMacBook-Pro:~ crissallan$ python3 train.py
Training set size: (2217, 20)
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initial loss 0.693146

**Comment by hollance** [comment]
What is the actual problem?

**Comment by ANYMS-A** [comment]
well, the script train.py  can't get the output as you showed in your article and got stuck as you see, it just output the value of Initial loss 0.693146. I was wondering is it wrong after I run split_data.py?because I put the voice.csv  into a wrong folder? I put all the scripts and data in one folder.

**Comment by hollance** [comment]
What do you mean it gets stuck? Does the process hang and do you need to press Ctrl+C to kill it, or does it exit immediately?

**Comment by ANYMS-A** [comment]
I need to press ctrl+c to kill it and after I pressing ctrl+c  I got the following lines:

^CTraceback (most recent call last):
  File "train.py", line 68, in <module>
    sess.run(train_op,feed_dict=feed)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
KeyboardInterrupt

**Comment by ANYMS-A** [comment]
hahahah!I 've solved this problem, and got the same output as you! thanks for your patient! keep learning!
